version: "3.9"

services:
  postgres:
    image: postgres:14
    container_name: asvp_postgres
    restart: unless-stopped
    profiles:
      - local-temporal
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  temporal:
    container_name: asvp_temporal
    image: temporalio/auto-setup:1.23.0
    restart: unless-stopped
    profiles:
      - local-temporal
    depends_on:
      - postgres
    environment:
      DB: postgresql
      DB_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PWD: ${POSTGRES_PASSWORD}
      POSTGRES_SEEDS: postgres
    ports:
      - "7233:7233"   

  temporal-web:
    image: temporalio/web:latest
    container_name: asvp_temporal_web
    restart: unless-stopped
    profiles:
      - local-temporal
    depends_on:
      - temporal
    environment:
      - TEMPORAL_GRPC_ENDPOINT=temporal:7233
      - TEMPORAL_PERMIT_WRITE_API=true
    ports:
      - "8233:8088"       

volumes:
  postgres_data:
  minio_data:
